<!-- PDF Footer (hidden on screen) -->
<div id="pdf-footer" class="d-none d-print-block">
    <div style="margin-top: 20px; padding-top: 12px; border-top: 2px solid #e2e8f0; display: flex; justify-content: space-between; align-items: center; font-size: 10px; color: #94a3b8;">
        <span>Generated by EduERP — {{ \App\Models\Setting::get('school_name', 'Enterprise School ERP') }}</span>
        <span>{{ now()->format('d M, Y — h:i A') }}</span>
    </div>
</div>
